### ISSUE TITLE
How to add "_" to email construct?

### ISSUE THREAD

**Issue by cortodamon** [UserCr4ig/Turbolehe#1]
How to modify the code in order to add "_" as an email construct criteria? (firstname_lastname@domain.com)
I've tried by adding:

```
    first_name.lower() + '_' + last_name.lower()[0] + domain,
    first_name.lower()[0] + '_' + last_name.lower() + domain,
    first_name.lower() + '_' + last_name.lower() + domain,
    last_name.lower() + '_' + first_name.lower() + domain,
    last_name.lower() + '_' + first_name.lower()[0] + domain,
    last_name.lower()[0] + '_' + first_name.lower() + domain,
```

but it would not work (maybe because of how ohlehe is built?)

**Comment by purrsec** [comment]
Hi damon, 

Check latest release. I added this.

https://github.com/UserCr4ig/Turbolehe/releases/tag/v0.2
